name: CI - Unit Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./EmployeeManagement.sln

      - name: Build the solution
        run: dotnet build 

      - name: Run unit tests with report
        run: dotnet test ./EmployeeManagement.Application.Tests/EmployeeManagement.Application.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./src/EmployeeManagement.Application.Tests/TestResults/TestResults.trx